- name: Install docker dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Create directory for Docker"s GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download Docker"s GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add docker repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | lower }} stable
    state: present

- name: Perform apt update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  notify: Reboot after install

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: docker
    append: true
