- name: Hide ESM package alerts in MOTD
  ansible.builtin.file:
    path: /var/lib/update-notifier/hide-esm-in-motd
    state: touch
    mode: "0640"
    modification_time: preserve
    access_time: preserve
  when: ansible_distribution == 'Ubuntu'
  notify: Refresh ESM MOTD
