- name: Copy sshd_config file
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config
    src: sshd_config
    owner: root
    group: root
    mode: "0600"

- name: Delete sshd_config.d directory if it exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d
    state: absent

- name: Check if there are any weak primes
  ansible.builtin.shell: awk "$5 < 3071" /etc/ssh/moduli
  register: moduli_check
  ignore_errors: true
  changed_when: false

- name: Filter /etc/ssh/moduli to only include strong primes
  ansible.builtin.shell: |
    awk "$5 >= 3071" /etc/ssh/moduli > /etc/ssh/moduli.tmp
    mv /etc/ssh/moduli.tmp /etc/ssh/moduli
  when: moduli_check.stdout_lines | length > 0
  changed_when: true
  notify: Restart SSHD service
