- name: Reboot after install
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible after Docker install"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
