- name: Hide help and news from MOTD
  ansible.builtin.file:
    path: "/etc/update-motd.d/{{ item }}"
    state: absent
  loop:
    - 10-help-text
    - 50-motd-news
    - 80-livepatch
    - 95-hwe-eol
  when: ansible_distribution == "Ubuntu"
