- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Start fail2ban service
  ansible.builtin.service:
    name: fail2ban
    state: started

- name: Enable fail2ban service
  ansible.builtin.service:
    name: fail2ban
    enabled: true

- name: Copy jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
    owner: root
    group: root

- name: Restart fail2ban service
  ansible.builtin.service:
    name: fail2ban
    state: restarted
