- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  when: ansible_os_family == "Debian"
  register: uu_installed

- name: Copy 20auto-upgrades file
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    mode: "0644"
  when: ansible_os_family == "Debian"
  register: au_copied

- name: Copy 50unattended-upgrades file
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
    mode: "0644"
  when: ansible_os_family == "Debian"
  register: uu_copied

- name: Restart unattended-upgrades service
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
    enabled: true
  when:
    - ansible_os_family == "Debian"
    - uu_installed.changed or au_copied.changed or uu_copied.changed
